### ISSUE TITLE
No Next Service Date is showing

### ISSUE THREAD

**Issue by UnconditionedLife** [UnconditionedLife/smum#112]
"Next Service date" should be showing with "Last Served date" --- all clients - all the time.

**Comment by UnconditionedLife** [comment]
An issue happened with the next service calculation being different for the receipt and the on-screen likely because of closure next Monday. The receipt was for today (Sat), but service was not available.

**Comment by UnconditionedLife** [comment]
"**validateServiceInterval**" function needs to use "**calFindOpenDate**" for the next service date calculated from calendar open and closed dates.

**Comment by scott-r** [comment]
I didn’t know about this bug, but it's another good reason for calling calFindOpenDate() from the Client code instead of Receipts.js.

	Scott

**Comment by UnconditionedLife** [comment]
I've used **calFindOpenDate()** to calculate both the **next service date** and **active buttons** this should correct the problems I observed.
