### ISSUE TITLE
UI: Last served text inaccurate (says last served 14 days ago when I added services today)

### ISSUE THREAD

**Issue by kjain14** [UnconditionedLife/smum#13]
![image](https://user-images.githubusercontent.com/8972749/35599817-9ae4b600-05df-11e8-9de2-b52cecd6f9b9.png)

**Comment by UnconditionedLife** [comment]
This was being hardcoded because saving functionality was not yet finished. Next push should fix it.

**Comment by UnconditionedLife** [comment]
I've made both the date and the last served dynamically update every 30 seconds. Last served is still not 100% because Services are not yet saved.

**Comment by UnconditionedLife** [comment]
The problem should now be solved.
