### ISSUE TITLE
UI: Displays "User not Authenticated" when signing in

### ISSUE THREAD

**Issue by kjain14** [UnconditionedLife/smum#14]
The UI says that I am not authenticated, but then lets me into the SMUM system.

**Comment by UnconditionedLife** [comment]
Was this when you first logged in? Has it repeated?

**Comment by kjain14** [comment]
Yes, it happened when I first logged in and has repeated.

**Comment by UnconditionedLife** [comment]
I have logged in with your credentials and was not able to see an authentication error. Are you using Chrome? Can you still see the error?

**Comment by kjain14** [comment]
I am using Chrome and still getting the error. Will try again today.

**Comment by kjain14** [comment]
Tried today, and error didn't occur.
