### ISSUE TITLE
FUTURE: Add back link to starting screen

### ISSUE THREAD

**Issue by kjain14** [UnconditionedLife/smum#15]
![image](https://user-images.githubusercontent.com/8972749/36947689-427f96ce-1f84-11e8-984e-ef1a5c75b002.png)
Currently no way to go back to the start screen upon logging in. Potentially navigate back to this screen upon clicking on the SMUM apple logo.

**Comment by UnconditionedLife** [comment]
Go back to what? A no client open situation, or do you mean logged out? I'm not understanding.

**Comment by kjain14** [comment]
I was thinking a no client open screen, that way they can't accidently edit the dependants of the client that was previously selected. For example when I search a client and get no results, I am still able to edit the previous client's info. I think from a UI perspective it would be better to have it clear all the other screens upon searching up a new client.

**Comment by UnconditionedLife** [comment]
Good points! I have cleared all service tabs. Plus removed some buttons that should not have been there on load. This should do what you suggested.
