### ISSUE TITLE
Admin pages cannot be refreshed

### ISSUE THREAD

**Issue by scott-r** [UnconditionedLife/smum#152]
When an admin page is reloaded, the URL is rewritten to /clients, taking you back to the start page. URL-based navigation needs to work consistently for all pages in the app.

**Comment by UnconditionedLife** [comment]
This turned out to be a simple fix. The isAdmin function (checks if the user is an ADMIN) was checking before the session was available and returning FALSE. I made the function return "undefined" if the session is not yet available, and the header router now ignores undefined.
