### ISSUE TITLE
Add admin screen to view error log

### ISSUE THREAD

**Issue by scott-r** [UnconditionedLife/smum#155]
Use public REST API to read error log entries and display on screen

**Comment by townsag** [comment]
Meeting Notes:
- add new tab to admin view that routes to error display page
- add error display page
- similar to list view on users page
- take start and end range as input on error 

Follow up Feature:
- cache amount of errors previously seen by admin account
- display red buddle icon over error tab with count of new unseen errors

**Comment by scott-r** [comment]
To clarify, there is no need to cache the number of error log entries previously seen. Just report the **current** number of errors in a bubble on the error tab.
