### ISSUE TITLE
UI: Sound playing when creating an invalid client, but no error box on some fields

### ISSUE THREAD

**Issue by kjain14** [UnconditionedLife/smum#16]
![image](https://user-images.githubusercontent.com/8972749/36947716-a2e62334-1f84-11e8-891a-6525ef707cbe.png)

**Comment by UnconditionedLife** [comment]
This should be corrected. There was a stray variable setting (hasError = false) which caused all the validations to work incorrectly. Please confirm and close.

**Comment by kjain14** [comment]
Error boxes work now.
