### ISSUE TITLE
Make the tables in Admin Service Types and Users fit the screen

### ISSUE THREAD

**Issue by UnconditionedLife** [UnconditionedLife/smum#163]
![CDD7C7E7-4FB3-44AB-B5B5-FCBDC337300E](https://github.com/UnconditionedLife/smum/assets/13460481/9f9ec2f3-e219-4a8a-b3b4-627d783cb75a)
![E12C1DC2-7A10-460F-9DE5-AD469216D45A](https://github.com/UnconditionedLife/smum/assets/13460481/a212b9a1-98ab-44cf-b89e-52e1c2b1593a)

**Comment by kjain14** [comment]
Made these tables scrollable, can explore making cards as next step potentially
