### ISSUE TITLE
Allowing the addition of new notes and services even when no clients are returned by the search query

### ISSUE THREAD

**Issue by kjain14** [UnconditionedLife/smum#19]
![image](https://user-images.githubusercontent.com/8972749/36947777-697de63a-1f85-11e8-8e76-9b66f2e40967.png)

**Comment by UnconditionedLife** [comment]
Tabs are now cleared, except for "New Client" button, if there is no current client. Please confirm and close.

**Comment by kjain14** [comment]
Tested and works now.
