### ISSUE TITLE
Not allowing creation of valid service type

### ISSUE THREAD

**Issue by kjain14** [UnconditionedLife/smum#21]
![image](https://user-images.githubusercontent.com/8972749/36947832-2ed83fde-1f86-11e8-9ae5-ccae8e7ed056.png)

**Comment by kjain14** [comment]
Works now after latest pull

**Comment by UnconditionedLife** [comment]
The not valid status has shown up randomly once or twice for me. I will keep trying to figure out why it's not passing validation.

**Comment by UnconditionedLife** [comment]
Was fixed some time ago.
