### ISSUE TITLE
Not allowing the creation of a valid user

### ISSUE THREAD

**Issue by kjain14** [UnconditionedLife/smum#22]
![image](https://user-images.githubusercontent.com/8972749/36947877-d09bb148-1f86-11e8-87b5-4cf09830bc3f.png)

**Comment by kjain14** [comment]
Works now after latest pull

**Comment by UnconditionedLife** [comment]
This may be the issue with the lookup validation, what is used to check that it is a valid select option. Let's leave it open for now. If you keep seeing this error please document here.

**Comment by UnconditionedLife** [comment]
Resolved some time ago.
