### ISSUE TITLE
Can leave zipcode, phone, email, and finance numbers blank and still save

### ISSUE THREAD

**Issue by kjain14** [UnconditionedLife/smum#24]
![image](https://user-images.githubusercontent.com/8972749/36948721-10dbc93e-1f94-11e8-8706-8620e558789b.png)

**Comment by UnconditionedLife** [comment]
Phone number and email are not required. But should be valid if entered. The zip code is required, but not the suffix. Please retest and close.

**Comment by kjain14** [comment]
Tested and works now.
