### ISSUE TITLE
Unable to change passwords even with matching passwords, getting this error

### ISSUE THREAD

**Issue by kjain14** [UnconditionedLife/smum#27]
![image](https://user-images.githubusercontent.com/8972749/36948838-83739df4-1f95-11e8-9de0-1bb8e9ce5433.png)

**Comment by UnconditionedLife** [comment]
I'm unable to reproduce this error. Can you please try again? Any special situations?

**Comment by kjain14** [comment]
Tried again to reproduce and error didn't occur.
