### ISSUE TITLE
Bug: First Step Pickup History Includes Adults as Serviced

### ISSUE THREAD

**Issue by kjain14** [UnconditionedLife/smum#38]
![image](https://user-images.githubusercontent.com/8972749/42302054-713de0c0-8036-11e8-9800-f2ddc674c199.png)

**Comment by UnconditionedLife** [comment]
The counts for "First Step 2018" should be "0" all the way across since no service has been delivered - only a voucher. The counts should only count children for "First Step Pickup".

@kjain14 please retest.
