### ISSUE TITLE
Bug: Added twelve dependents, but all not saved

### ISSUE THREAD

**Issue by kjain14** [UnconditionedLife/smum#40]
![image](https://user-images.githubusercontent.com/8972749/42302435-7e227baa-8038-11e8-8285-83cb3c864e43.png)

Steps to reproduce: 

1. Go to 8888
2. Add a dependent for each of the grade levels
3. Make the dependents one male and one female for each grade distribution
4. Press save

**Comment by UnconditionedLife** [comment]
Unfortunately, this seems to have been a long-standing bug.

@kjain14 please test again.

**Comment by kjain14** [comment]
Tested and issue is resolved.
