### ISSUE TITLE
Bug: Grade Counts Inaccurate

### ISSUE THREAD

**Issue by kjain14** [UnconditionedLife/smum#42]
Grade Distribution for Test Client:

![image](https://user-images.githubusercontent.com/8972749/42302728-562f8b68-803a-11e8-940a-7800e42912cd.png)

Report for Counts:
![image](https://user-images.githubusercontent.com/8972749/42302772-8e3c3970-803a-11e8-9aca-f56a238787cf.png)

**Comment by UnconditionedLife** [comment]
Counts seem to be ok. The problem might be that you are not accounting for the fact that the grades in the client records are last school year's while the counts show next school year's grades. Also, the function assumes that 12th graders will graduate.

@kjain14 please confirm.

**Comment by kjain14** [comment]
Tested and counts seem to be working accurately.
