### ISSUE TITLE
Bug: First Step Pickup Registering as Service when Voucher

### ISSUE THREAD

**Issue by kjain14** [UnconditionedLife/smum#43]
![image](https://user-images.githubusercontent.com/8972749/42327917-9cb01102-808a-11e8-98f8-bd8ac07057ee.png)

**Comment by UnconditionedLife** [comment]
@kjain14  please make sure you have the most current codebase.

**Comment by kjain14** [comment]
Tested and the fulfillment seems to be working accurately.
