### ISSUE TITLE
Feature: Validate Next Visit Date with Closed Dates

### ISSUE THREAD

**Issue by UnconditionedLife** [UnconditionedLife/smum#51]
- Calculate "next visit" date for client receipt then validate against closed dates
   - if the date is same as a "closed date" then subtract a day
   - loop through until an open day is found that is a minimum of 7 days from the current visit.
   - if no open days are found between 7 and 14 days, then add a day to the initial next visit
   - loop through until an open day is found

**Comment by UnconditionedLife** [comment]
Looks like the best was to create and store the closed dates is not as an array of all closed dates, but a set of 3 nested arrays:
1) single days
2) days of the week (ie. Sunday)
3) days of week and weeks of the month (ie. (2nd Saturday)

@scott-r Does this make sense to you?

**Comment by scott-r** [comment]
This approach is fine for now, and I will continue to use it as in the existing code. Eventually, we should probably migrate to a library that implements the full complement of recurring date patterns as specified in RFC 5545.
