### ISSUE TITLE
USDA Food service enabled even though last visit was too recent

### ISSUE THREAD

**Issue by scott-r** [UnconditionedLife/smum#73]
Problem observed on 12/15/2018 for client 2271.
History shows
- 11/16/2018 (29 days ago): USDA Food
- 12/3/2018 (12 days ago): Non-USDA Food
- 12/15/2018: USDA Food

**Comment by UnconditionedLife** [comment]
I think we should look at this as part of an overall redesign of the client.lastServed object I'm proposing in issue #75. I think the logic around the service button display needs a rethink and that starts with making sure we are capturing the right information at the client record level so as not to repeatedly query the history table.  - Your thoughts, Scott?

**Comment by scott-r** [comment]
Great. I've been thinking about this today and was going to email you some ideas. I'll go look at the issue you opened and add my comments there. 
Scott


Sent from my Samsung Galaxy smartphone.
-------- Original message --------From: Jose Leal <notifications@github.com> Date: 12/18/18  11:24 AM  (GMT-08:00) To: UnconditionedLife/smum <smum@noreply.github.com> Cc: Scott Rotondo <rotondo@gmx.com>, Author <author@noreply.github.com> Subject: Re: [UnconditionedLife/smum] USDA Food service enabled even though
  last visit was too recent (#73) 
I think we should look at this as part of an overall redesign of the client.lastServed object I'm proposing in issue #75. I think the logic around the service button display needs a rethink and that starts with making sure we are capturing the right information at the client record level so as not to repeatedly query the history table.  - Your thoughts, Scott?

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub, or mute the thread.
{"api_version":"1.0","publisher":{"api_key":"05dde50f1d1a384dd78767c55493e4bb","name":"GitHub"},"entity":{"external_key":"github/UnconditionedLife/smum","title":"UnconditionedLife/smum","subtitle":"GitHub repository","main_image_url":"https://github.githubassets.com/images/email/message_cards/header.png","avatar_image_url":"https://github.githubassets.com/images/email/message_cards/avatar.png","action":{"name":"Open in GitHub","url":"https://github.com/UnconditionedLife/smum"}},"updates":{"snippets":[{"icon":"PERSON","message":"@UnconditionedLife in #73: I think we should look at this as part of an overall redesign of the client.lastServed object I'm proposing in issue #75. I think the logic around the service button display needs a rethink and that starts with making sure we are capturing the right information at the client record level so as not to repeatedly query the history table.  - Your thoughts, Scott?"}],"action":{"name":"View Issue","url":"https://github.com/UnconditionedLife/smum/issues/73#issuecomment-448339469"}}}
[
{
"@context": "http://schema.org",
"@type": "EmailMessage",
"potentialAction": {
"@type": "ViewAction",
"target": "https://github.com/UnconditionedLife/smum/issues/73#issuecomment-448339469",
"url": "https://github.com/UnconditionedLife/smum/issues/73#issuecomment-448339469",
"name": "View Issue"
},
"description": "View this Issue on GitHub",
"publisher": {
"@type": "Organization",
"name": "GitHub",
"url": "https://github.com"
}
}
]

**Comment by UnconditionedLife** [comment]
This has been resolved.
